// Emoji de bandera por nombre de selección (en inglés, como lo devuelve FotMob).
// Fallback 🏳️ cuando no está en el mapa; en la UI se prefiere el escudo real (logoUrl).
const FLAGS: Record<string, string> = {
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Brazil: "🇧🇷",
  Canada: "🇨🇦",
  Colombia: "🇨🇴",
  Croatia: "🇭🇷",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Iran: "🇮🇷",
  Italy: "🇮🇹",
  Japan: "🇯🇵",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  Nigeria: "🇳🇬",
  Norway: "🇳🇴",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Senegal: "🇸🇳",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Spain: "🇪🇸",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Tunisia: "🇹🇳",
  Ukraine: "🇺🇦",
  Uruguay: "🇺🇾",
  "United States": "🇺🇸",
  USA: "🇺🇸",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Algeria: "🇩🇿",
  "Ivory Coast": "🇨🇮",
  Cameroon: "🇨🇲",
  "Saudi Arabia": "🇸🇦",
  "Costa Rica": "🇨🇷",
  Jordan: "🇯🇴",
  Uzbekistan: "🇺🇿",
  "New Zealand": "🇳🇿",
  "Cape Verde": "🇨🇻",
  Curacao: "🇨🇼",
  Haiti: "🇭🇹",
  Czechia: "🇨🇿",
  "Czech Republic": "🇨🇿",
  "Bosnia and Herzegovina": "🇧🇦",
  Turkiye: "🇹🇷",
  Turkey: "🇹🇷",
  Serbia: "🇷🇸",
  Greece: "🇬🇷",
  Romania: "🇷🇴",
  Hungary: "🇭🇺",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  Albania: "🇦🇱",
  "Northern Ireland": "🇬🇧",
  "Republic of Ireland": "🇮🇪",
  Ireland: "🇮🇪",
  Iceland: "🇮🇸",
  Finland: "🇫🇮",
  "DR Congo": "🇨🇩",
  Mali: "🇲🇱",
  "Burkina Faso": "🇧🇫",
  Angola: "🇦🇴",
  Zambia: "🇿🇲",
  Bolivia: "🇧🇴",
  Venezuela: "🇻🇪",
  Chile: "🇨🇱",
  Honduras: "🇭🇳",
  Jamaica: "🇯🇲",
  Iraq: "🇮🇶",
  "United Arab Emirates": "🇦🇪",
  Oman: "🇴🇲",
  Bahrain: "🇧🇭",
  China: "🇨🇳",
  Thailand: "🇹🇭",
  Indonesia: "🇮🇩",
  Vietnam: "🇻🇳",
};

export function flagFor(name: string): string {
  return FLAGS[name] ?? "🏳️";
}
